# %%
# AUTO-GENERATED by scripts/generate_factor_notebooks.py from
# factsheet-content/factors.yaml -- do not edit by hand. Re-run the
# generator (or the "Generate Notebooks" workflow) to refresh.
import sys
from pathlib import Path

_repo_root = Path.cwd()
while not (_repo_root / "analysis").is_dir() and _repo_root != _repo_root.parent:
    _repo_root = _repo_root.parent
sys.path.insert(0, str(_repo_root))

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from unravel_client import get_portfolio_returns

from analysis.utils import get_env

UNRAVEL_API_KEY = get_env("UNRAVEL_API_KEY")

# Every single-factor portfolio in factsheet-content/factors.yaml.
portfolios = [
    "altair.40",
    "margin_risk.40",
    "retail_flow.40",
    "mean_reversion_enhanced.40",
    "instantaneous_momentum.40",
    "polaris.40",
    "relative_illiquidity.40",
    "supply_velocity.40",
    "momentum_enhanced.40",
    "mean_reversion.40",
    "trend_longonly_adaptive.40",
    "carry_enhanced.40",
    "instantaneous_volatility.40",
    "open_interest_divergence.40",
    "momentum.40",
]

returns_df = pd.DataFrame(
    {
        portfolio: get_portfolio_returns(id=portfolio, api_key=UNRAVEL_API_KEY)
        for portfolio in portfolios
    }
)

# %%

correlation_matrix = returns_df.corr()

plt.figure(figsize=(16, 13))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    center=0,
    square=True,
    fmt=".2f",
    cbar_kws={"shrink": 0.8},
)
plt.title("Cross-Sectional Returns Correlation Matrix")
plt.tight_layout()
plt.show()

# %%
