"""Generate the per-factor AlphaLens notebooks from the factor catalog.

Single source of truth is ``factsheet-content/factors.yaml``. For every
factor in the catalog this writes:

    notebooks/factor_analysis_<id>.py      jupytext "percent" script
    notebooks/factor_analysis_<id>.ipynb   notebook converted from the script

It also (re)generates ``notebooks/factor_returns_correlation.{py,ipynb}``
covering *every* portfolio in the catalog.

Usage:
    python -m scripts.generate_factor_notebooks            # write + convert
    python -m scripts.generate_factor_notebooks --execute  # also run them
    python -m scripts.generate_factor_notebooks altair     # one factor

The ``--execute`` flag runs the notebooks in-place with nbconvert and
requires ``UNRAVEL_API_KEY`` in the environment (it is wired from repo
secrets in the "Generate Notebooks" CI workflow).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
FACTORS_YAML = REPO_ROOT / "factsheet-content" / "factors.yaml"
NOTEBOOKS_DIR = REPO_ROOT / "notebooks"

# Prepended to every generated script so `import analysis` resolves whether
# the notebook is run from notebooks/ (Jupyter's default cwd) or the repo
# root (nbconvert in CI). The `analysis` helper package lives at the root.
_PATH_BOOTSTRAP = '''import sys
from pathlib import Path

_repo_root = Path.cwd()
while not (_repo_root / "analysis").is_dir() and _repo_root != _repo_root.parent:
    _repo_root = _repo_root.parent
sys.path.insert(0, str(_repo_root))
'''

_GENERATED_BANNER = (
    "# AUTO-GENERATED by scripts/generate_factor_notebooks.py from\n"
    "# factsheet-content/factors.yaml -- do not edit by hand. Re-run the\n"
    "# generator (or the \"Generate Notebooks\" workflow) to refresh.\n"
)

_FACTOR_TEMPLATE = '''# %%
{banner}
{bootstrap}
from unravel_client import (
    get_historical_universe,
    get_portfolio_factors_historical,
    get_prices,
    get_tickers,
)

from analysis.alphalens import factor_analysis
from analysis.utils import get_env

UNRAVEL_API_KEY = get_env("UNRAVEL_API_KEY")

# {name} -- portfolio {portfolio_id}
portfolio = "{id}"
universe_size = "{universe}"

available_tickers = get_tickers(
    id=portfolio,
    api_key=UNRAVEL_API_KEY,
    universe_size=universe_size,
    exchange=None,
)
historical_factors = get_portfolio_factors_historical(
    id=portfolio, tickers=available_tickers, api_key=UNRAVEL_API_KEY
)
underlying = get_prices(tickers=available_tickers, api_key=UNRAVEL_API_KEY)

# Restrict the analysis to the *dynamic* point-in-time universe rather than
# every ticker that was ever tradeable. get_historical_universe returns a
# boolean membership matrix (dates x tickers); masking the raw factor with it
# drops each asset on the days it was out of universe, so AlphaLens scores
# the factor on the universe we actually trade.
universe = get_historical_universe(
    size=universe_size,
    api_key=UNRAVEL_API_KEY,
    start_date=str(historical_factors.index.min().date()),
    end_date=str(historical_factors.index.max().date()),
)
membership = (
    universe.reindex(index=historical_factors.index)
    .ffill()
    .reindex(columns=historical_factors.columns)
    .fillna(False)
    .astype(bool)
)
restricted_factors = historical_factors.where(membership)

columns_intersection = restricted_factors.columns.intersection(underlying.columns)
factor_analysis(restricted_factors[columns_intersection], underlying)

# %%
'''

_CORRELATION_TEMPLATE = '''# %%
{banner}
{bootstrap}
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from unravel_client import get_portfolio_returns

from analysis.utils import get_env

UNRAVEL_API_KEY = get_env("UNRAVEL_API_KEY")

# Every single-factor portfolio in factsheet-content/factors.yaml.
portfolios = [
{portfolio_list}
]

returns_df = pd.DataFrame(
    {{
        portfolio: get_portfolio_returns(id=portfolio, api_key=UNRAVEL_API_KEY)
        for portfolio in portfolios
    }}
)

# %%

correlation_matrix = returns_df.corr()

plt.figure(figsize=(16, 13))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    center=0,
    square=True,
    fmt=".2f",
    cbar_kws={{"shrink": 0.8}},
)
plt.title("Cross-Sectional Returns Correlation Matrix")
plt.tight_layout()
plt.show()

# %%
'''


class Factor:
    __slots__ = ("id", "name", "portfolio_id", "universe")

    def __init__(self, entry: dict) -> None:
        self.id = entry["id"]
        self.name = entry["name"]
        self.portfolio_id = entry["portfolio_id"]
        self.universe = str(entry["default_universe"])


def load_factors() -> list[Factor]:
    raw = yaml.safe_load(FACTORS_YAML.read_text())
    return [Factor(entry) for entry in raw["factors"]]


def _write(path: Path, content: str) -> None:
    path.write_text(content)
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def write_scripts(factors: list[Factor]) -> list[Path]:
    NOTEBOOKS_DIR.mkdir(exist_ok=True)
    written: list[Path] = []

    for factor in factors:
        path = NOTEBOOKS_DIR / f"factor_analysis_{factor.id}.py"
        _write(
            path,
            _FACTOR_TEMPLATE.format(
                banner=_GENERATED_BANNER.rstrip(),
                bootstrap=_PATH_BOOTSTRAP,
                name=factor.name,
                portfolio_id=factor.portfolio_id,
                id=factor.id,
                universe=factor.universe,
            ),
        )
        written.append(path)

    # The correlation notebook always covers the full catalog, regardless of
    # any per-factor subset passed on argv.
    all_portfolios = [f.portfolio_id for f in load_factors()]
    portfolio_list = "\n".join(f'    "{pid}",' for pid in all_portfolios)
    corr_path = NOTEBOOKS_DIR / "factor_returns_correlation.py"
    _write(
        corr_path,
        _CORRELATION_TEMPLATE.format(
            banner=_GENERATED_BANNER.rstrip(),
            bootstrap=_PATH_BOOTSTRAP,
            portfolio_list=portfolio_list,
        ),
    )
    written.append(corr_path)
    return written


def to_notebook(py_file: Path) -> Path:
    ipynb = py_file.with_suffix(".ipynb")
    subprocess.run(
        ["jupytext", "--to", "notebook", "--output", str(ipynb), str(py_file)],
        check=True,
        capture_output=True,
        text=True,
    )
    print(f"  converted {ipynb.relative_to(REPO_ROOT)}")
    return ipynb


LOGS_DIR = NOTEBOOKS_DIR / "_execution_logs"
REPORT = NOTEBOOKS_DIR / "_execution_report.md"


def execute(ipynb: Path) -> tuple[bool, str]:
    """Execute a notebook in place. Returns (ok, captured_output).

    Never raises on a notebook error -- the output is captured so the CI run
    can commit a diagnosable report back to the branch (we have no other way
    to read Actions logs from here)."""
    print(f"  executing {ipynb.relative_to(REPO_ROOT)} ...")
    proc = subprocess.run(
        [
            "jupyter",
            "nbconvert",
            "--to",
            "notebook",
            "--execute",
            "--inplace",
            # jupytext does not embed a kernelspec, so pin one explicitly.
            "--ExecutePreprocessor.kernel_name=python3",
            "--ExecutePreprocessor.timeout=1800",
            str(ipynb),
        ],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    ok = proc.returncode == 0
    if not ok:
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
        (LOGS_DIR / f"{ipynb.stem}.log").write_text(output)
        print(f"    FAILED ({ipynb.stem}) -- see notebooks/_execution_logs/")
    return ok, output


def main(argv: list[str]) -> None:
    do_execute = "--execute" in argv
    wanted = [a for a in argv if not a.startswith("--")]

    factors = load_factors()
    if wanted:
        selected = [f for f in factors if f.id in set(wanted)]
        missing = set(wanted) - {f.id for f in selected}
        if missing:
            raise SystemExit(f"Unknown factor ids: {sorted(missing)}")
        factors = selected

    print(f"Generating notebooks for {len(factors)} factor(s):")
    scripts = write_scripts(factors)

    print("Converting to notebooks:")
    notebooks = [to_notebook(p) for p in scripts]

    if do_execute:
        print("Executing notebooks (requires UNRAVEL_API_KEY):")
        failures: list[tuple[str, str]] = []
        for nb in notebooks:
            ok, output = execute(nb)
            if not ok:
                # Keep the last ~60 lines -- enough for the traceback.
                tail = "\n".join(output.strip().splitlines()[-60:])
                failures.append((nb.stem, tail))

        lines = [
            "# Notebook execution report",
            "",
            f"Total: {len(notebooks)} | "
            f"Passed: {len(notebooks) - len(failures)} | "
            f"Failed: {len(failures)}",
            "",
        ]
        for name, tail in failures:
            lines += [f"## {name}", "", "```", tail, "```", ""]
        REPORT.write_text("\n".join(lines) + "\n")
        print(f"Wrote {REPORT.relative_to(REPO_ROOT)}")

        if failures:
            raise SystemExit(
                f"{len(failures)} notebook(s) failed to execute: "
                f"{[n for n, _ in failures]}"
            )

    print("Done.")


if __name__ == "__main__":
    main(sys.argv[1:])
